# Generated by Django 4.1 on 2022-08-29 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inset',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images/', verbose_name='画像アップロード用')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('roomid', models.CharField(db_index=True, max_length=20, verbose_name='教室ID')),
                ('groupname', models.CharField(max_length=100, verbose_name='団体名')),
                ('campus', models.IntegerField(default=0, verbose_name='INIAD or WELLB')),
                ('floor', models.IntegerField(default=1, verbose_name='階')),
                ('only_stamp', models.BooleanField(default=False, verbose_name='スタンプラリー専用かどうか(優先度高:こちらがTrueの場合強制的にスタンプラリー専用になります)')),
                ('have_a_stamp', models.BooleanField(default=False, verbose_name='スタンプラリー対象団体かどうか')),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='stamp/', verbose_name='スタンプの素材画像')),
                ('serial', models.IntegerField(verbose_name='表示順序')),
                ('position_y', models.IntegerField(default=0, verbose_name='素材の上側のポジション(px)')),
                ('position_x', models.IntegerField(default=0, verbose_name='素材の左側のポジション(px)')),
                ('story', models.TextField(blank=True, null=True, verbose_name='ストーリー用')),
            ],
        ),
        migrations.CreateModel(
            name='StampCourse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='スタンプラリーコースの名称')),
                ('main_color', models.CharField(max_length=6, verbose_name='サイトデザインの色(メイン)')),
                ('sub_color', models.CharField(max_length=6, verbose_name='サイトデザインの色(サブ)')),
                ('activation', models.BooleanField(default=False, verbose_name='スタンプラリーを有効化するかどうか')),
                ('finished', models.BooleanField(default=False, verbose_name='終了後スタンプラリーを見れるかどうか')),
                ('background', models.ImageField(upload_to='stampbg/', verbose_name='スタンプラリーの背景画像')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='QRコードのID')),
                ('nickname', models.CharField(max_length=20, verbose_name='ニックネーム')),
                ('first_name', models.CharField(max_length=20, verbose_name='名')),
                ('last_name', models.CharField(max_length=20, verbose_name='姓')),
                ('ruby_first_name', models.CharField(max_length=20, verbose_name='メイ')),
                ('ruby_last_name', models.CharField(max_length=20, verbose_name='セイ')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('address', models.CharField(max_length=30, verbose_name='都道府県市区町村')),
                ('age', models.IntegerField(default=0, verbose_name='年代')),
                ('job', models.CharField(max_length=20, verbose_name='職業')),
                ('design', models.IntegerField(default=0, verbose_name='ネームカードのデザイン')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備考欄')),
                ('number', models.IntegerField(verbose_name='ネームカードにプリントされるID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='初回登録日時')),
                ('is_preregistration', models.BooleanField(default=False, verbose_name='事前登録かどうか')),
                ('is_handedover', models.BooleanField(default=False, verbose_name='お渡し済みかどうか')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='StampHistory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('got', models.ManyToManyField(blank=True, related_name='history', to='fes2022.stamp')),
                ('stampcourse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='fes2022.stampcourse')),
            ],
        ),
        migrations.AddField(
            model_name='stamp',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stamps', to='fes2022.stampcourse'),
        ),
        migrations.CreateModel(
            name='NowRoom',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時')),
                ('inorout', models.BooleanField(default=True, verbose_name='入室or退室')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fes2022.room', verbose_name='Roomの教室ID(id)との紐づけ')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fes2022.visitor', verbose_name='VisitorのユーザID(id)との紐づけ')),
            ],
        ),
        migrations.CreateModel(
            name='NowCampus',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時')),
                ('inorout', models.BooleanField(default=True, verbose_name='入構or退構')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fes2022.visitor', verbose_name='VisitorのユーザID(id)との紐づけ')),
            ],
        ),
    ]
