# Generated by Django 4.1 on 2022-09-19 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=30, verbose_name='機能名')),
                ('page', models.CharField(max_length=30, verbose_name='ページ名')),
                ('users', models.ManyToManyField(blank=True, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
