# Generated by Django 4.1 on 2022-09-23 01:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fes2022', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyRoomQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now, verbose_name='確認時刻')),
                ('ready', models.BooleanField(default=False, verbose_name='準備完了かどうか')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyRoomQRdevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(blank=True, null=True, verbose_name='準備完了時刻')),
                ('ready', models.BooleanField(default=False, verbose_name='準備完了かどうか')),
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fes2022.placeid')),
                ('readyroomqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.readyroomqr')),
            ],
        ),
        migrations.AddField(
            model_name='readyroomqr',
            name='device',
            field=models.ManyToManyField(through='administration.ReadyRoomQRdevice', to='fes2022.placeid'),
        ),
    ]
