# Generated by Django 4.1 on 2022-09-07 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fes2022.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inset',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=fes2022.models.Inset.get_image_path, verbose_name='画像アップロード用')),
                ('alt', models.TextField(verbose_name='画像の説明(alt属性)')),
            ],
        ),
        migrations.CreateModel(
            name='NamecardDesign',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('serial', models.IntegerField(verbose_name='通し番号')),
                ('img', models.ImageField(upload_to=fes2022.models.NamecardDesign.get_image_path, verbose_name='デザイン画像')),
                ('name', models.CharField(max_length=50, verbose_name='ネームカードデザインの名前')),
                ('campus', models.IntegerField(choices=[(0, 'INIAD'), (1, 'WELLB')], default=0, verbose_name='INIAD or WELLB')),
                ('numofprints', models.IntegerField(default=500, verbose_name='印刷数')),
                ('numofremaining', models.IntegerField(default=-1, verbose_name='残り')),
                ('is_subject_secret', models.BooleanField(default=False, verbose_name='シークレットか')),
                ('is_only_advance', models.BooleanField(default=False, verbose_name='事前登録限定か')),
                ('text', models.TextField(verbose_name='デザインの説明')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=100, verbose_name='団体名')),
                ('campus', models.IntegerField(choices=[(0, 'INIAD'), (1, 'WELLB')], default=0, verbose_name='INIAD or WELLB')),
                ('floor', models.IntegerField(default=1, verbose_name='階')),
                ('room_number', models.IntegerField(verbose_name='教室名かドア番号の小さいほう')),
                ('only_stamp', models.BooleanField(default=False, verbose_name='スタンプラリー専用かどうか(優先度高:こちらがTrueの場合強制的にスタンプラリー専用になります)')),
                ('have_a_stamp', models.BooleanField(default=False, verbose_name='スタンプラリー対象団体かどうか')),
                ('pop', models.ImageField(upload_to='ipad_pop/', verbose_name='QRコード読み取りiPadに表示する画像')),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=fes2022.models.Stamp.get_image_path, verbose_name='スタンプの素材画像')),
                ('serial', models.IntegerField(verbose_name='表示順序')),
                ('position_y', models.IntegerField(default=0, verbose_name='素材の上側のポジション(px)')),
                ('position_x', models.IntegerField(default=0, verbose_name='素材の左側のポジション(px)')),
                ('story', models.TextField(blank=True, null=True, verbose_name='ストーリー用')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stamp', to='fes2022.room')),
            ],
        ),
        migrations.CreateModel(
            name='StampCourse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='スタンプラリーコースの名称')),
                ('main_color', models.CharField(max_length=6, verbose_name='サイトデザインの色(メイン)')),
                ('sub_color', models.CharField(max_length=6, verbose_name='サイトデザインの色(サブ)')),
                ('activation', models.BooleanField(default=False, verbose_name='スタンプラリーを有効化するかどうか')),
                ('finished', models.BooleanField(default=False, verbose_name='終了後スタンプラリーを見れるかどうか')),
                ('background', models.ImageField(upload_to=fes2022.models.StampCourse.get_image_path, verbose_name='スタンプラリーの背景画像')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='QRコードのID')),
                ('management_uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='管理用uuid')),
                ('date', models.DateField(verbose_name='入場日')),
                ('nickname', models.CharField(max_length=20, verbose_name='ニックネーム')),
                ('first_name', models.CharField(max_length=20, verbose_name='名')),
                ('last_name', models.CharField(max_length=20, verbose_name='姓')),
                ('ruby_first_name', models.CharField(max_length=20, verbose_name='メイ')),
                ('ruby_last_name', models.CharField(max_length=20, verbose_name='セイ')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('address', models.CharField(max_length=20, verbose_name='住所')),
                ('age', models.IntegerField(default=0, verbose_name='年代')),
                ('gender', models.CharField(max_length=8, verbose_name='性別')),
                ('major_subject', models.CharField(max_length=20, verbose_name='専攻/希望分野')),
                ('job', models.CharField(max_length=20, verbose_name='職業')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備考欄')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='初回登録日時')),
                ('is_verified_email', models.BooleanField(default=False, verbose_name='使用可能なメールアドレスかどうか')),
                ('is_preregistration', models.BooleanField(default=False, verbose_name='事前登録かどうか')),
                ('is_printed', models.BooleanField(default=False, verbose_name='印刷完了かどうか')),
                ('is_handedover', models.BooleanField(default=False, verbose_name='お渡し済みかどうか')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors_select', to='fes2022.namecarddesign', verbose_name='ネームカードのデザイン')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='StampHistory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('got', models.ManyToManyField(blank=True, related_name='history', to='fes2022.stamp')),
                ('stampcourse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='fes2022.stampcourse')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stamp_history', to='fes2022.visitor')),
            ],
        ),
        migrations.AddField(
            model_name='stamp',
            name='stampcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='fes2022.stampcourse'),
        ),
        migrations.CreateModel(
            name='PlaceID',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('placeid', models.IntegerField(db_index=True, verbose_name='場所ID')),
                ('placenum', models.IntegerField(verbose_name='場所番号')),
                ('door_number', models.IntegerField(verbose_name='教室番号かドア番号')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceIDs', to='fes2022.room')),
            ],
        ),
        migrations.CreateModel(
            name='NowRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時')),
                ('inorout', models.BooleanField(default=True, verbose_name='入室or退室')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nowroom', to='fes2022.room', verbose_name='Roomの教室ID(id)との紐づけ')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nowroom', to='fes2022.visitor', verbose_name='VisitorのユーザID(id)との紐づけ')),
            ],
        ),
        migrations.CreateModel(
            name='NowCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時')),
                ('inorout', models.BooleanField(default=True, verbose_name='入構or退構')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nowcampus', to='fes2022.visitor', verbose_name='VisitorのユーザID(id)との紐づけ')),
            ],
        ),
    ]
