# Generated by Django 4.1 on 2022-10-23 06:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fes2022', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('count', models.IntegerField(default=0, verbose_name='今の人数')),
                ('unique_count', models.IntegerField(default=0, verbose_name='総人数')),
                ('total_count', models.IntegerField(default=0, verbose_name='総延べ人数')),
                ('pop', models.ImageField(upload_to='ipad_pop/', verbose_name='QRコード読み取りiPadに表示する画像')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fes2022.room'),
        ),
    ]
