# Generated by Django 4.1 on 2022-10-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fes2022', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fes2022.room'),
        ),
    ]
