# Generated by Django 4.1 on 2022-09-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=10, verbose_name='何の日か')),
                ('key', models.CharField(max_length=5, verbose_name='アルファベット')),
                ('date', models.DateField(verbose_name='期限など')),
            ],
        ),
    ]
