# Generated by Django 4.1 on 2022-10-14 17:29

from django.db import migrations, models
import django.db.models.deletion
import fes2022.portal.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fes2022', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clatter_item',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='アイテム名')),
                ('img', models.ImageField(blank=True, null=True, upload_to=fes2022.portal.models.Clatter_item.get_image_path, verbose_name='画像')),
                ('text', models.TextField(blank=True, null=True, verbose_name='テキスト')),
                ('is_html', models.BooleanField(default=False, verbose_name='テキストをHTMLとして解釈するかどうか')),
                ('position_x', models.IntegerField(verbose_name='取得後の展示位置(x)')),
                ('position_y', models.IntegerField(verbose_name='取得後の展示位置(y)')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開設定')),
            ],
        ),
        migrations.CreateModel(
            name='Team3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=30, verbose_name='ページ名')),
                ('move_to', models.CharField(blank=True, max_length=30, null=True, verbose_name='非公開時の遷移先')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開設定')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_public', models.BooleanField(verbose_name='公開前')),
                ('pre', models.BooleanField(verbose_name='事前登録期間')),
                ('fes', models.BooleanField(verbose_name='当日')),
                ('finished', models.BooleanField(verbose_name='終了後')),
            ],
        ),
        migrations.CreateModel(
            name='Got_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(blank=True, related_name='取得したアイテム', to='portal.clatter_item')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fes2022.visitor')),
            ],
        ),
    ]
